### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by caschoff** [ansible-buch/ansible-buch#1]
Auf Seite 128 steht unten "Die Dokuentation" statt "Die Doku**m**entation"...

**Comment by ansible-buch** [comment]
Hi!
Vielen Dank, ich hab's in meinen Sourcen korrigiert. Die 3. Auflage wird dann einen Fehler weniger haben :-)

Viele Grüße und weiter viel Spaß und Erfolg mit Ansible!
