### ISSUE TITLE
SSH-Verbindungen bei Standard-Image

### ISSUE THREAD

**Issue by ghost** [ansible-buch/ansible-buch#2]
Hallo Herr Miesen,

vorweg möchte ich sagen, dass Ihr Buch große Klasse ist und Ihr Schreibstil zum Lesen anregt und unterhaltsam ist.

Ich habe bereits mehrfach einzelne Kapitel durchgearbeitet und bin nun dabei das Buch chronologisch durchzuarbeiten. Im Kapitel 1.6 wird die Verbindung per SSH mittels Auth-Key vom Control Host zu den Target Hosts zum ersten Mal hergestellt. Hier schreiben Sie, dass nach einer Erzeugung mittels `ssh-keygen` die Schlüssel per `ssh-copy-id vagrant@<host>` auf die Target Hosts übertragen werden soll. Jenes wird jedoch mit einem "Permission denied" abgelehnt. Das Problem sollte sein, dass eine SSH-Verbindung per Passwort standardmäßig deaktiviert ist.

```
# /etc/ssh/sshd_config
[...]
PasswordAuthentication No
```

Der Unterschied zu den Schritten in ihrem Buch ist, dass Sie das Image _bento/debian-11_ nutzen. Ich hingegen habe das Standard-Image _debian/bullseye64_ genutzt. Ich denke es wäre vlt. sinnvoll einen Hinweis in der Richtung im Buch zu ergänzen, sodass zukünftige Leser nicht vor dem gleichen Problem wie ich stehen und sich wundern, warum der beschriebene Schritt nicht das gleiche Ergebnis erzeugt.

**Comment by ansible-buch** [comment]
Hallo Herr Timptner!

Danke für Ihre Nachricht, freut mich sehr, dass Ihnen mein Buch gefällt :-)

Ich habe soeben mal die Zeit gefunden, Ihr Setup nachzustellen. Habe mit folgendem kleinen Vagrantfile eine
debian/bullseye64-Box hochgefahren:

```
NETWORK_PREFIX = "192.168.150"

Vagrant.configure("2") do |config|

  config.vm.define "ansible2" do |ansible2|
    ansible2.vm.box = "debian/bullseye64"
    ansible2.vm.hostname = "ansible2"
    ansible2.vm.network :private_network, ip: "#{NETWORK_PREFIX}.100"
  end
end
```

Ich kann danach den User `vagrant` mit dem Passwort `vagrant` problemlos erreichen und demzufolge auch mit ssh-copy-id einen Schlüssel dort hinterlegen. Eigentlich sind doch auch alle Vagrant-Boxes so gebaut (dachte ich).

Deswegen kann ich jetzt aus der Entfernung nicht sagen, was bei Ihnen anders war. Wichtig ist ja letztlich, dass Sie nun ein funktionierendes Laborsetup haben, mit dem Sie arbeiten können.

Weiter viel Spaß mit Ansible, viele Grüße,
  Axel Miesen

**Comment by ghost** [comment]
Hallo Herr Miesen,

ich habe es eben noch einmal getestet und die Standard-Boxen (`debian/bullseye64`, `debian/bookworm64`) haben alle in der `/etc/ssh/sshd_config` die Authentifizerung mittels Passwort deaktiviert. Aber wenn es bei Ihnen funktioniert, dann muss es wohl ein Fehler meinerseits sein.

Gibt es einen Grund, warum Sie die Boxen von _bento_ gegenüber den Standard-Boxen von _vargant_ bevorzugen? 🙂

**Comment by ansible-buch** [comment]
Hallo Herr Timptner!

Schon merkwürdig mit dem SSH-Zugang... Schicken Sie mir doch aus Spaß gerne mal die sshd_config von einem taufrischen System!

Was Bento angeht: Ich glaube, damals bei der 1. Auflage waren Bento diejenigen, die sehr gut gepflegte Images für Debian, Ubuntu, openSUSE und Rocky im Angebot hatten, und die überdies für virtualbox und vmware_desktop zur Verfügung standen. Letzteres gab dann für mich den Ausschlag, weil ich zu der Zeit noch nicht mit Virtualbox unter Linux gearbeitet habe.

Viele Grüße und schönen Abend!
